var _arAdmShow=[],_arAdmNotShow=[],_arAdmCp=[],_chkPr=!1,_arNPr=[],_trackingSend=false;
window.ADS_CHECKER={RAND:Math.random(),getPath2Check:function(a){var c=document.URL,d=document.referrer;return("Site:Pageurl"==a?c.replace(/\?i=([0-9]+)&bz=([0-9]+)&z=([0-9]+)#([0-9_0-9]+)/g,""):d.replace(/\?i=([0-9]+)&bz=([0-9]+)&z=([0-9]+)#([0-9_0-9]+)/g,"")).toLowerCase()},plugin:new function(){var a,c,d,b,h,f=this;f.installed=!1;f.raw="";f.major=-1;f.minor=-1;f.revision=-1;f.revisionStr="";var n=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(a){return v(a)}},{name:"ShockwaveFlash.ShockwaveFlash.6",
version:function(a){var b="6.0.r21";try{a.AllowScriptAccess="always",b=v(a)}catch(c){}return b}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(a){return v(a)}}],v=function(a){var b=-1;try{b=a.GetVariable("$version")}catch(c){}return b};f.majorAtLeast=function(a){return f.major>=a};f.minorAtLeast=function(a){return f.minor>=a};f.revisionAtLeast=function(a){return f.revision>=a};f.versionAtLeast=function(a){var b=[f.major,f.minor,f.revision],c=Math.min(b.length,arguments.length);for(i=0;i<
c;i++)if(b[i]>=arguments[i]){if(!(i+1<c&&b[i]==arguments[i]))return!0}else return!1};if(navigator.plugins&&0<navigator.plugins.length){if((n=navigator.mimeTypes)&&n["application/x-shockwave-flash"]&&n["application/x-shockwave-flash"].enabledPlugin&&n["application/x-shockwave-flash"].enabledPlugin.description){var w=n["application/x-shockwave-flash"].enabledPlugin.description,G=w,n=G.split(/ +/),w=n[2].split(/\./),n=n[3];a=G;c=parseInt(w[0],10);d=parseInt(w[1],10);b=n;h=parseInt(n.replace(/[a-zA-Z]/g,
""),10)||f.revision;f.raw=a;f.major=c;f.minor=d;f.revisionStr=b;f.revision=h;f.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript){w=-1;for(G=0;G<n.length&&-1==w;G++){a=-1;try{a=new ActiveXObject(n[G].name)}catch(r){a={activeXError:!0}}a.activeXError||(f.installed=!0,w=n[G].version(a),-1!=w&&(a=w,b=a.split(","),c=parseInt(b[0].split(" ")[1],10),d=parseInt(b[1],10),h=parseInt(b[2],10),b=b[2],f.raw=a.replace("Shockwave Flash ",""),f.major=c,f.minor=d,f.revision=h,f.revisionStr=
b))}}},checker:function(a,c,d){c=this.getPath2Check(c);switch(d){case "==":return c==a;case "!=":return c!=a;case "=~":return ADS_CHECKER.stripos(c,a,0);case "!~":return!ADS_CHECKER.stripos(c,a,0);case "=x":return a=RegExp(a),a.test(c);case "!x":return a=RegExp(a),!a.test(c)}return!1},getQuery:function(a){var a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),c=RegExp("[\\?&]"+a+"=([^&#]*)"),c=c.exec(document.referrer);return null==c?(c=RegExp("[\\?&]"+a+"=([^&#]*)"),c=c.exec(document.URL),null==c?"":
decodeURIComponent(c[1].replace(/\+/g," "))):decodeURIComponent(c[1].replace(/\+/g," "))},getElementTop:function(a){if(document.getElementById)var c=document.getElementById(a);else document.all&&(c=document.all[a]);if(null!=c){yPos=c.offsetTop;for(tempEl=c.offsetParent;null!=tempEl;)yPos+=tempEl.offsetTop,tempEl=tempEl.offsetParent;return yPos}return 0},checker_checker:function(a,c){if(a){for(var d=a.length,b="",h="",f=0;f<d;f++)if(void 0==a[f].data){for(var n="",v=0;v<a[f].length;v++)h="or"==a[f][v].join?
"||":"&&",n+=(0!=v?h:"")+ADS_CHECKER.checker(a[f][v].data,a[f][v].type,a[f][v].logic);b+=(0!=f?c:"")+"("+n+")"}else b+=(0!=f?c:"")+ADS_CHECKER.checker(a[f].data,a[f].type,a[f].logic);return b}return!1},setStorage:function(a,c,d,b,h,f){"localStorage"in window&&null!==window.localStorage?(ADS_CHECKER.lcStorage.set_item(a,c,d),("__R"!=a||"__RC"!=a)&&ADS_CHECKER.setCookie(a,"",d,b,h,f)):ADS_CHECKER.setCookie(a,c,d,b,h,f)},getStorage:function(a){return"localStorage"in window&&null!==window.localStorage?
"__R"==a||"__RC"==a?ADS_CHECKER.getCookie(a):ADS_CHECKER.lcStorage.get_item(a):ADS_CHECKER.getCookie(a)},lcStorage:{timestamp:"timestamp_",get_exprises:function(a,c,d,b){c=a.indexOf(c,d);d=a.length-1;return-1!=c?(b=a.indexOf(b,c),-1==b&&(b=d),a.substring(c,b)):""},set_item:function(a,c,d){var b="",h=(new Date).getTime(),f=this.timestamp,h=0==d||""==d?h+864E5:h+6E4*d,b="_azs"==a?";":",",d=this.get_exprises(c,f,0,b),c=""==d?c+(f+h.toString()+b):c.replace(d,f+h.toString());localStorage.setItem(a,c)},
get_item:function(a,c){var d=localStorage.getItem(a),b=(new Date).getTime(),h=this.timestamp;if(""==d||null==d)return"";endchar="_azs"==a?";":",";var f=this.get_exprises(d,h,0,endchar),f=f.replace(h,"");if(""==f||isNaN(parseInt(f))||parseInt(f)<b)return"";"undefined"!=typeof c&&(d=d.replace(h+f+endchar,""));return d},remove_item:function(a){localStorage.removeItem(a)},flush:function(){localStorage.clear()}},rand:function(a,c){var d=arguments.length;if(0==d)a=0,c=2147483647;else if(1==d)throw Error("Error");
return Math.floor(Math.random()*(c-a+1))+a},subCookie:function(a,c,d){c=a.indexOf(c,d);d=a.length-1;if(-1!=c){var b=a.indexOf(";",c);-1==b&&(b=d);return a.substring(c,b)}return""},popup_setCookie:function(a,c,d,b,h,f){var d=(new Date(+new Date+6E5)).toGMTString(),a=[a+"="+escape(c)],n;for(n in d={expires:d,path:b,domain:h})d[n]&&a.push(n+"="+d[n]);return f&&a.push("secure"),document.cookie=a.join(";"),!0},setCookie:function(a,c,d,b,h,f){(new Date).getTime();var b=""==b?"/":b,d=0==d||""==d?(new Date(+new Date+
864E5)).toGMTString():(new Date(+new Date+6E4*d)).toGMTString(),a=[a+"="+escape(c)],n;for(n in d={expires:d,path:b,domain:h})d[n]&&a.push(n+"="+d[n]);return f&&a.push("secure"),document.cookie=a.join(";"),!0},getCookie:function(a){return 0<document.cookie.length&&(c_start=document.cookie.indexOf(a+"="),-1!=c_start)?(c_start=c_start+a.length+1,c_end=document.cookie.indexOf(";",c_start),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,c_end))):""},in_array:function(a,
c,d){var b=!1,h,d=!!d;for(h in c)if(d&&c[h]===a||!d&&c[h]==a){b=!0;break}return b},in_array_position:function(a,c,d){for(var b=0,d=!!d,h=0,f=c.length;h<f;h++){if(d&&c[h]===a||!d&&c[h]==a)return h;b++}return-1},array_duplicate:function(a,c){var d=[];if(!(0==a.length||0==c.length))for(var b=0,h=a.length;b<h;b++)ADS_CHECKER.in_array(a[b],c)&&(d[d.length]=a[b]);return d},array_diff:function(a,c){for(var d=[],b=0,h=a.length;b<h;b++)ADS_CHECKER.in_array(a[b],c)||(d[d.length]=a[b]);return d},stripos:function(a,
c,d){a=(a+"").toLowerCase();c=(c+"").toLowerCase();return-1!==a.indexOf(c,d)},processClick:function(a,c){for(var d=c.length,b=0;b<d;b++){var h=document.createElement("iframe");h.width=0;h.height=0;h.style.border=0;h.src=c;document.getElementById(a).appendChild(h)}},randBanner:function(){return 0==Math.floor(100*Math.random())%2?0:1}};var ADS_Location=ADS_CHECKER.getStorage("__R"),ADS_City=ADS_CHECKER.getStorage("__RC");ADS_CHECKER.flash=ADS_CHECKER.plugin.installed;
if(""!=ADS_Location&&(0<=parseInt(ADS_Location)&&3>=parseInt(ADS_Location)?(""==ADS_City||"undefined"==typeof ADS_City)&&ADS_CHECKER.setStorage("__RC",ADS_Location,"","/"):(4==parseInt(ADS_Location)||7<=parseInt(ADS_Location)&&31>parseInt(ADS_Location)?ADS_CHECKER.setStorage("__R","1","","/"):31<=parseInt(ADS_Location)||51>=parseInt(ADS_Location)?ADS_CHECKER.setStorage("__R","2","","/"):ADS_CHECKER.setStorage("__R","3","","/"),ADS_CHECKER.setStorage("__RC",ADS_Location,"","/")),"0"==ADS_Location&&
"0"!=ADS_City))4==parseInt(ADS_City)||7<=parseInt(ADS_City)&&31>parseInt(ADS_City)?(ADS_Location=1,ADS_CHECKER.setStorage("__R","1","","/")):31<=parseInt(ADS_City)||51>=parseInt(ADS_City)?(ADS_Location=2,ADS_CHECKER.setStorage("__R","2","","/")):100>=parseInt(ADS_City)&&(ADS_Location=3,ADS_CHECKER.setStorage("__R","3","","/"));
function banner(a){if(a){var a={bid:parseInt(a.bid),title:a.title,type:a.type,link:a.link,src:a.src,alt:a.alt?a.alt:"",location:a.location,width:parseInt(a.width),height:parseInt(a.height),created:a.created?a.created:null,expired:a.expired?a.expired:null,slotIdx:a.slotIdx,attr:a.attr,terms:a.terms,clicks:a.clicks?a.clicks:null,views:a.views?a.views:null,cpname:a.cpname,counter:a.counter,iframe:a.iframe,sort:a.sort,cpm:a.cpm?a.cpm:0,link_clicks:a.link_clicks,link_views:a.link_views,weight:a.weight?
a.weight:0===a.weight?0:1,gr:a.gr?a.gr:0,pr:a.pr?a.pr:"",bannertype:a.bannertype?a.bannertype:0,ckPr:!1,bool:!1},c;for(c in a)this[c]=a[c]}}
banner.prototype.logging=function(a,c,d,b){var h=this.link?this.link:"-1";c?(c="http://logging.admicro.vn/_adv.gif",h=b?encodeURIComponent(c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_random="+d):c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_random="+d):(c="http://logging.admicro.vn/_adc.html",h=
b?encodeURIComponent(c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_rehttp="+escape(h)+"&adm_random="+d):c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_rehttp="+encodeURIComponent(h)+"&adm_random="+d);return h};
banner.prototype.renderLinkViews=function(){var a="";if(null!=this.link_views){var c=this.link_views.length;if(document.images)for(var d=[],b=0;b<c;b++)d[b]=new Image,d[b].src=this.link_views[b];else a+='<div style="position:absolute;background:url('+this.link_views[b]+');height:0; width:0" ><span style="height:0; width:0"></span></div>'}return a};
banner.prototype.renderLinkClicks=function(a){var c="";if(null!=this.link_clicks){for(var c="swf"==this.type?c+'onmousedown="':c+'onclick="',c=c+("ADS_CHECKER.processClick('"+a+"',["),a=this.link_clicks.length,d=0;d<a;d++)c+="'"+this.link_clicks[d]+"'"+(d<a-1?",":"");c+=']);"'}return c};
banner.prototype.renderBanner=function(a,c,d,b,h){h='<div id="'+a+'" class="'+h+'" '+(b?'style="display:none"':"")+">";switch(this.type){case "gif":case "jpeg":case "png":h+=this.renderBannerImage(a,c,d,b);break;case "swf":h+=this.renderBannerFlash(a,c,d,b);break;case "html":var a=""==ADS_Location||isNaN(parseInt(ADS_Location))||"0"==ADS_Location?1:parseInt(ADS_Location),b=this.src,f=ADS_CHECKER.getQuery("z");parseInt(ADS_CHECKER.getQuery("bz"));var n=parseInt(ADS_CHECKER.getQuery("i"));""!=f&&""!=
n?(b=b.replace(/(ssvzone|pluszone)_([0-9]+).js/,"$1_$2_"+a+".js?random="+Math.random()),b=b.replace(/cpmzone_([0-9]+).js/,"cpmzone_$1.js?random="+Math.random())):b=b.replace(/(ssvzone|pluszone)_([0-9]+).js/,"$1_$2_"+a+".js");h+=(b+"").replace(/\0/g,"0").replace(/\\([\\'"])/g,"$1")}this.counter&&(document.images?(new Image).src=this.logging(c,!0,d):h+='<div style="background:url('+this.logging(c,!0,d)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>');
return h+this.renderLinkViews()+"</div>"};banner.prototype.renderBannerImage=function(a,c,d){var b='<img border="0" id="'+a+'" src="'+this.src+'"'+(this.width?' width="'+this.width+'"':"")+(this.height?' height="'+this.height+'"':"");if(this.attr)for(var h in this.attr)b+=" "+h+'="'+this.attr[h]+'"';b+=" "+this.renderLinkClicks(a)+" />";return this.link?'<a href="'+this.logging(c,!1,d)+'" target="_blank">'+b+"</a>":b};
banner.prototype.renderBannerFlash=function(a,c,d){var b="",h=this.link?"alink1="+this.logging(c,!1,d,!0)+"&amp;atar1=_blank":"",f=!1;if(this.attr)for(var n in this.attr)"flashvars"==n&&(this.attr[n]=h+"&amp;"+this.attr[n],f=!0),b+=" "+n+'="'+this.attr[n]+'"';""!=h&&!f&&(b+=' flashvars="'+h+'"');if(ADS_CHECKER.flash)return"<embed "+this.renderLinkClicks(a)+' src="'+this.src+'" height="'+this.height+'" alt="'+this.alt+'" align="middle" width="'+this.width+'" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" '+
b+' allowscriptaccess="always" wmode="transparent" quality="high" />';if(null!=this.alt&""!=this.alt){b='<img border="0" id="'+a+'" src="'+this.alt+'"'+(this.width?' width="'+this.width+'"':"")+(this.height?' height="'+this.height+'"':"");if(this.attr)for(n in this.attr)b+=" "+n+'="'+this.attr[n]+'"';b+=" "+this.renderLinkClicks(a)+" />";return this.link?'<a href="'+this.logging(c,!1,d)+'" target="_blank">'+b+"</a>":b}return"<embed "+this.renderLinkClicks(a)+' src="'+this.src+'" height="'+this.height+
'" alt="'+this.alt+'" align="middle" width="'+this.width+'" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" '+b+' allowscriptaccess="always" wmode="transparent" quality="high" />'};banner.prototype.time=function(){return ads_time_server?ads_time_server:Math.round((new Date).getTime()/1E3)};banner.prototype.checkViews=function(a){a=a.substring(0,a.length-1);eval("view = view_"+a+this.bid);return!0};
banner.prototype.checkClicks=function(a){a=a.substring(0,a.length-1);eval("click = click_"+a+this.bid);return!0};banner.prototype.checkExpired=function(){var a=this.time();return this.created<a&&null==this.expired||this.created<a&&a<this.expired?!1:!0};banner.prototype.checkInvalid=function(a){return this.checkExpired()||!this.checkViews(a)||!this.checkClicks(a)?!1:!0};
banner.prototype.checkPr=function(){var a=document.URL,c=this.pr.split("|");this.ckPr=!1;for(var d=0,b=c.length;d<b;d++)if(-1!=a.indexOf(c[d]))return _chkPr=this.ckPr=!0;return!1};
banner.prototype.process=function(){if(this.terms){for(var a=this.terms,c=a.length,d="",b="",h=0;h<c;h++)0!=h&&(b="or"==a[h].join?"||":"&&"),d=a[h].channel?d+(b+("!~"==a[h].logic?"!":"")+"("+ADS_CHECKER.checker_checker(a[h].data,"=="==a[h].logic?"&&":"||")+")"):d+(b+ADS_CHECKER.checker(a[h].data,a[h].type,a[h].logic));this.bool=eval(d)}else this.bool=!0;"undefined"!=typeof __arCPM4K&&(0!=__arCPM4K.length&&ADS_CHECKER.in_array(this.bid,__arCPM4K))&&(this.bool=!1);1===this.gr&&ADS_CHECKER.in_array(parseInt(this.cpname),
_arAdmNotShow)&&(this.bool=!1);""!=this.pr?this.bool=this.checkPr():_chkPr&&(this.bool=!1);!ADS_CHECKER.flash&&(""==this.alt&&"swf"==this.type)&&(this.bool=!1);""!=ADS_Location&&(a=this.location,a="undefined"==a||null==a?0:a,a=","+(""==a?0:a)+",",c=","+ADS_Location+",",d=","+ADS_City+",",this.bool=this.bool&&(",,"==a||",1,2,3,"==a||",0,"==a||-1!=a.toString().indexOf(d)||-1!=a.toString().indexOf(c)?!0:!1))};
function zone(a,c,d,b,h){var a={banners:[],zoneid:a?a:-1,width:d,height:b,attr:h,style:c,share:c.share?c.share:3,slots:null,time:1E4,preload_time:3E3,rand_num:ADS_CHECKER.RAND,theme:[],run_fix:!1,cpm:null,cpd:null,ie:"Opera"==navigator.appName||"Microsoft Internet Explorer"==navigator.appName},f;for(f in a)this[f]=a[f]}zone.prototype.removeHidden=function(){};
zone.prototype.removeHtml=function(a){for(var c=1;c<=this.style.slot;c++){var d=a.indexOf("slot"+c+"_content"),b=a.lastIndexOf("<div",d),h=a.indexOf("</div>",d);0<=d&&(d=a.substring(b,h+6),a=a.replace(d,""))}return a};zone.prototype.mkRandCPM=function(a){var c=0,d;for(d in a)c+=parseInt(a[d]);var b=[],h=0;for(d in a)b.push((0<h?b[h-1]:0)+Math.floor(1E3*parseInt(a[d])/c)/1E3),h++;a=b.length;0<a&&(b[a-1]=1);return b};
zone.prototype.choseRandom=function(a){for(var c=Math.random(),d=0;d<a.length;d++)if(c<=a[d])return d;return 0};
zone.prototype.getBannerRun=function(a){var c=parseInt(ADS_CHECKER.getQuery("z")),d=parseInt(ADS_CHECKER.getQuery("bz")),b=parseInt(ADS_CHECKER.getQuery("z1")),h=parseInt(ADS_CHECKER.getQuery("bz1"));ADS_CHECKER.getStorage("_azs");var f=this.zoneid,n=this.style.slot,v=this.style.sort_banner_slot,w=!1,G=[],r=[],s=[],z=[],t=[],G=[],g=[],o=[],p=0,m={},j=!1,y=[],C=[],q=[],x=[],l=[];this.spamCpd=[];this.spamBidCpd=[];this.spamlstCp=[];this.bz=0;for(var b=isNaN(b)?0:b,h=isNaN(h)?0:h,c=isNaN(c)?0:c,d=isNaN(d)?
0:d,e=0;e<this.style.slot;e++){g[e]=[];o[e]=[];s[e]=0;if(0!=v[e+1])for(var k=0;k<v[e+1].length;k++)g[e][k]=[],o[e][k]=[];G[e]=[];r[e]=e+1;s[e]=0}ADS_City=""==ADS_City?0:ADS_City;var B=[],D=[],F=[];if("101"==ADS_City)for(var E in a)k=new banner(a[E]),k.process(),!_chkPr&&(k.bool&&k.location==ADS_City)&&(B.push(k.bid),F.push({bid:k.bid,slotIdx:k.slotIdx,sort:k.sort,cpm:k.cpm}),D.push(k.slotIdx));for(E in a)if(k=new banner(a[E]),"undefined"!=typeof a[E].bid){var A=parseInt(a[E].bid.toString()),H=a[E].slotIdx;
if(1==a[E].weight||0==a[E].weight)z.push(A);else if(d==A)z.push(A);else for(e=0;e<a[E].weight;e++)z.push(A+"_"+e);k.process();k.ckPr&&l.push(k.bid);w=!1;if(k.bool||k.bool&&(A==d&&f==c||A==h&&f==b)){1===k.gr&&(C.push(k.bid),ADS_CHECKER.in_array(parseInt(k.cpname),x)||x.push(parseInt(k.cpname)),q.push({bid:k.bid,cid:parseInt(k.cpname),Idx:k.slotIdx,sort:k.sort}));var J=!1;if(0===k.weight){var I=ADS_CHECKER.getStorage("_popup"),K="w"+k.bid.toString()+":",L=Math.floor((new Date).getTime()/1E3);if(""==
I)J=!0,I=K+L.toString()+";";else{var M=ADS_CHECKER.subCookie(I,K,0);""==M?(J=!0,I+=K+L.toString()+";"):600<=L-parseInt(M.replace(K,""))&&(J=!0,I=I.replace(M+";",K+L.toString()+";"))}J&&ADS_CHECKER.setStorage("_popup",I,10,"/")}w=w?w:A==d&&f==c||A==h&&f==b;p=A==d&&f==c||A==h&&f==b?H:p;this.bz=w?A:this.bz;!1===w&&(!0===J&&f!=c)&&(w=!0,p=H,this.bz=A);t.push(A);1<=parseInt(H)&&G[H-1].push(A);if(1==k.cpm)if(0<k.sort&&0!=v[H])if(1===a[E].weight||0===a[E].weight)g[H-1][k.sort-1].push(A);else if(this.bz==
A)g[H-1][k.sort-1].push(A);else for(e=0;e<a[E].weight;e++)g[H-1][k.sort-1].push(A+"_"+e);else{if(0==k.sort)if(1===a[E].weight||0===a[E].weight)g[H-1].push(A);else if(this.bz==A)g[H-1].push(A);else for(e=0;e<a[E].weight;e++)g[H-1].push(A+"_"+e)}else if(8==k.bannertype&&(j||(j=!0),m[k.bid]={bid:k.bid,slotIdx:k.slotIdx,sort:k.sort,weight:k.weight},ADS_CHECKER.in_array(k.slotIdx,y)||y.push(k.slotIdx)),0<k.sort&&0!=v[H])if(1===a[E].weight||0===a[E].weight)o[H-1][k.sort-1].push(A);else if(this.bz==A)o[H-
1][k.sort-1].push(A);else for(e=0;e<a[E].weight;e++)o[H-1][k.sort-1].push(A+"_"+e);else if(0==k.sort)if(1===a[E].weight||0===a[E].weight)o[H-1].push(A);else if(this.bz==A)o[H-1].push(A);else for(e=0;e<a[E].weight;e++)o[H-1].push(A+"_"+e)}}if(0<l.length){if(0<_arNPr.length){e=0;for(c=_arNPr.length;e<c;e++)t=document.getElementById("ads_zone"+_arNPr[e]),"undefined"!=typeof t&&null!=typeof t&&(t.style.display="none")}for(var u=this.style.sort_banner_slot,t=l,e=0;e<n;e++)if(0==u[e+1])0<o[e].length&&(o[e]=
ADS_CHECKER.array_duplicate(l,o[e])),0<g[e].length&&(g[e]=ADS_CHECKER.array_duplicate(l,g[e]));else{k=0;for(d=u[e+1].length;k<d;k++)0<o[e][k].length&&(o[e][k]=ADS_CHECKER.array_duplicate(l,o[e][k])),0<g[e][k].length&&(g[e][k]=ADS_CHECKER.array_duplicate(l,g[e][k]))}}else if(!_chkPr&&(_arNPr.push(f),0<B.length))if(l=this.style.slots_rotate,null!=l){e=0;for(c=l.length;e<c;e++)if(b=ADS_CHECKER.array_duplicate(D,l[e]),0<b.length){k=0;for(d=l[e].length;k<d;k++)if(ADS_CHECKER.in_array(l[e][k],b))if(0==
v[l[e][k]])o[l[e][k]-1]=ADS_CHECKER.array_duplicate(B,o[l[e][k]-1]),g[l[e][k]-1]=ADS_CHECKER.array_duplicate(B,g[l[e][k]-1]);else for(u in F)ADS_CHECKER.in_array(F[u].slotIdx,b)&&(g[l[e][k]-1][F[u].sort-1]=ADS_CHECKER.array_duplicate(B,g[l[e][k]-1][F[u].sort-1]),o[l[e][k]-1][F[u].sort-1]=ADS_CHECKER.array_duplicate(B,o[l[e][k]-1][F[u].sort-1]));else if(0==v[l[e][k]])o[l[e][k]-1]=[],g[l[e][k]-1]=[];else{u=0;for(n=v[l[e][k]].length;u<n;u++)g[l[e][k]-1][v[l[e][k]][u]-1]=[],o[l[e][k]-1][v[l[e][k]][u]-
1]=[]}}}else for(e=1;e<=n;e++)if(ADS_CHECKER.in_array(e,D))if(0==v[e])o[e-1]=ADS_CHECKER.array_duplicate(B,o[e-1]),g[e-1]=ADS_CHECKER.array_duplicate(B,g[e-1]);else for(u in F)F[u].slotIdx==e&&(g[e-1][F[u].sort-1]=ADS_CHECKER.array_duplicate(B,g[e-1][F[u].sort-1]),o[e-1][F[u].sort-1]=ADS_CHECKER.array_duplicate(B,o[e-1][F[u].sort-1]));this.spamCpd=C;this.spamBidCpd=q;this.spamlstCp=x;q=[];x=0;if(!w&&j&&0==C.length&&!_chkPr){j=this.style.slots_rotate;w=this.style.effect;for(e in m)if(q.push(m[e].bid),
2==w[m[e].slotIdx]&&(k=v[m[e].slotIdx],D=B=0,C=m[e].slotIdx,n=m[e].sort,0==g[C-1][n-1].length)){u=0;for(c=k.length;u<c;u++)k[u]==m[e].sort?D=o[C-1][n-1].length:B=Math.max(B,o[C-1][k[u]-1].length);if(D<B){c=B-D;for(u=0;u<c;u++)k=1!=c?"0_"+u:0,o[C-1][n-1].push(k),ADS_CHECKER.in_array(0,t)||t.push(0),ADS_CHECKER.in_array(k,z)||(x++,z.push(k),q.push(k))}}C=r;if(null!=j){e=0;for(c=j.length;e<c;e++)if(u=ADS_CHECKER.array_duplicate(j[e],y),C=ADS_CHECKER.array_diff(C,j[e]),0<u.length){B=!1;k=0;for(d=j[e].length;k<
d;k++)if(2==w[j[e][k]]){u=0;for(n=v[j[e][k]].length;u<n;u++)if(0<g[j[e][k]-1][u].length){B=!0;break}}else if(0<g[j[e][k]-1].length){B=!0;break}if(!B){k=D=0;for(d=j[e].length;k<d;k++)if(2==w[j[e][k]]){u=B=0;for(n=v[j[e][k]].length;u<n;u++)B=Math.max(B,o[j[e][k]-1][u].length);D+=B}else D+=o[j[e][k]-1].length;B=this.share-D;D=ADS_CHECKER.array_diff(j[e],y);if(0<D.length){F=Math.floor(Math.random()*D.length);for(u=0;u<B;u++){if(2==w[D[F]]){d=l=k=0;for(n=v[D[F]].length;d<n;d++)b=o[D[F]-1][d].length,k=
Math.max(k,b),k==b&&(l=d);k="0_"+x;o[D[F]-1][l].push(k)}else k="0_"+x,o[D[F]-1].push(k);ADS_CHECKER.in_array(0,t)||t.push(0);ADS_CHECKER.in_array(k,z)||(x++,z.push(k),q.push(k))}}}}}for(e in m)if(ADS_CHECKER.in_array(m[e].slotIdx,C))if(2==w[m[e].slotIdx]){if(0==g[m[e].slotIdx-1][m[e].sort-1].length){y=this.share-o[m[e].slotIdx-1][m[e].sort-1].length;for(u=0;u<y;u++)k="0_"+x,o[m[e].slotIdx-1][m[e].sort-1].push(k),ADS_CHECKER.in_array(0,t)||t.push(0),ADS_CHECKER.in_array(k,z)||(x++,z.push(k),q.push(k))}}else if(0==
g[m[e].slotIdx-1].length){y=this.share-o[m[e].slotIdx-1].length;for(u=0;u<y;u++)k="0_"+x,o[m[e].slotIdx-1].push(k),ADS_CHECKER.in_array(0,t)||t.push(0),ADS_CHECKER.in_array(k,z)||(x++,z.push(k),q.push(k))}}if(0==t.length)this.drawEmpty();else{this.abr=t;this.cpm=g;this.cpd=o;this.arrb=z;this.trk=0!=p?!0:!1;this.trks=p;this.arrSlot=r;this.arr7k=q;if(0<o.length){e=0;for(c=o.length;e<c;e++)if(0==v[e+1])s[e]=o[e].length;else{k=0;for(d=v[e+1].length;k<d;k++)s[e]=Math.max(s[e],o[e][k].length)}this.slotSize=
s}this.drawBannerRun(a)}};zone.prototype.resetParam=function(){1!=ADS_CHECKER.getQuery("admdebug")&&(this.style=this.arrSlot=this.cookie=this.html=null)};zone.prototype.renderIframe=function(a,c,d,b){return'<iframe src="" style="border:none;" width="'+d+'" height="'+b+'" marginheight="0" align="top" scrolling="No" frameborder="0" hspace="0" vspace="0" class="'+c+'" id="'+a+'"><html><head><style>body{margin:0;}</style></head><body></body></html></iframe>'};
zone.prototype.fillterCpdShow=function(a,c){var d=this.style.effect,b=this.spamBidCpd,h=this.cpd;ADS_CHECKER.in_array(a.bid,this.spamCpd)&&(ADS_CHECKER.in_array(parseInt(a.cpname),_arAdmShow)||_arAdmShow.push(parseInt(a.cpname)));if(2===d[a.slotIdx])for(var f=0,n=b.length;f<n;f++){b[f].Idx==a.slotIdx&&(b[f].cid==parseInt(a.cpname)&&b[f].sort>a.sort)&&(this.cpd[a.slotIdx-1][b[f].sort-1]=[b[f].bid]);if(0===a.gr&&a.slotIdx==b[f].Idx&&a.sort==b[f].sort||0===a.gr&&a.slotIdx!=b[f].Idx||1===a.gr&&a.slotIdx==
b[f].Idx&&a.sort==b[f].sort&&parseInt(a.cpname)!=b[f].cid||parseInt(a.cpname)!=b[f].cid&&b[f].Idx!=a.slotIdx&&0<c.length&&ADS_CHECKER.in_array(b[f].Idx,c))ADS_CHECKER.in_array(b[f].cid,_arAdmNotShow)||_arAdmNotShow.push(b[f].cid);if(a.slotIdx==b[f].Idx&&b[f].sort==a.sort||a.slotIdx==b[f].Idx&&ADS_CHECKER.in_array(b[f].cid,_arAdmNotShow))this.cpd[a.slotIdx-1][b[f].sort-1]=ADS_CHECKER.array_diff(h[a.slotIdx-1][b[f].sort-1],[b[f].bid])}else{f=0;for(n=b.length;f<n;f++)if(b[f].Idx==a.slotIdx&&a.bid!=b[f].bid&&
!ADS_CHECKER.in_array(b[f].cid,_arAdmShow)||0<c.length&&b[f].Idx!=a.slotIdx&&ADS_CHECKER.in_array(b[f].Idx,c)&&!ADS_CHECKER.in_array(b[f].cid,_arAdmShow))ADS_CHECKER.in_array(b[f].cid,_arAdmNotShow)||_arAdmNotShow.push(b[f].cid)}f=0;for(n=b.length;f<n;f++)ADS_CHECKER.in_array(b[f].cid,_arAdmNotShow)&&(2==d[b[f].Idx]?this.cpd[b[f].Idx-1][b[f].sort-1]=ADS_CHECKER.array_diff(this.cpd[b[f].Idx-1][b[f].sort-1],[b[f].bid]):this.cpd[b[f].Idx-1]=ADS_CHECKER.array_diff(this.cpd[b[f].Idx-1],[b[f].bid]))};
zone.prototype.drawBannerRun=function(a){var c=this.style.html,d=ADS_CHECKER.getStorage("_azs"),b=this.subCookie(d,"Ver:",0),h=this.style.slots_rotate,f=this.style.effect,n=this.arrSlot,v=this.style.sort_banner_slot,w=this.style.banner_default,G=this.share,r=this.zoneid,s=this.arrb,z=[];""==b&&(d="Ver:5;");this.cookie=d;var t=[];if(this.trk){if(0==v[this.trks])this.cpd[this.trks-1]=[this.bz];else for(var b=0,g=this.cpd[this.trks-1].length;b<g;b++)if(-1!=this.cpd[this.trks-1][b].indexOf(this.bz)||
-1!=this.cpm[this.trks-1][b].indexOf(this.bz)){this.cpd[this.trks-1][b]=[this.bz];break}if(h)for(var b=0,o=h.length;b<o;b++)if(n=ADS_CHECKER.array_diff(n,h[b]),-1!=h[b].indexOf(this.trks))t.push(this.trks.toString());else{var p=this.getSlotRun(r,b,h[b],d),d=this.cookie;p&&t.push(p.toString())}}else if(h){b=0;for(o=h.length;b<o;b++){n=ADS_CHECKER.array_diff(n,h[b]);if(p=this.getSlotRun(r,b,h[b],d))for(var d=ADS_CHECKER.array_diff(h[b],[parseInt(p.replace(/_[0-9]+/g,""))]),m=this.spamBidCpd.length,
j=0;j<m;j++)ADS_CHECKER.in_array(this.spamBidCpd[j].Idx,d)&&(ADS_CHECKER.in_array(this.spamBidCpd[j].cid,_arAdmNotShow)||_arAdmNotShow.push(this.spamBidCpd[j].cid));d=this.cookie;p&&t.push(p.toString())}}for(var p=this.cpd,y=this.cpm,b=0;b<t.length;b++){var m=t[b].split("_"),C="";if(-1!=t[b].indexOf("m")){o=[];for(j=0;j<h[b].length;j++)if(2==f[h[b][j]]){for(var q=0,g=0;g<this.cpm[h[b][j]-1].length;g++)0<this.cpm[h[b][j]-1][g].length&&(q=Math.max(q,this.cpm[h[b][j]-1][g].length));if(0!=q)for(g=0;g<
q;g++)o.push(h[b][j]+"_"+g)}else if(0<this.cpm[h[b][j]-1].length)for(g=0;g<this.cpm[h[b][j]-1].length;g++)o.push(h[b][j]+"_"+g);j="z"+r+"m"+b+":";q=this.subCookie(d,j,0);if(""==q)0<o.length&&(g=ADS_CHECKER.rand(0,o.length-1),m[0]=o[g].replace(/_([0-9]+)/,""),d+=j+o[g]+";");else if(g=q.replace(j,"").split(","),0<ADS_CHECKER.array_diff(g,o).length)g=ADS_CHECKER.rand(0,o.length-1),m[0]=o[g].replace(/_([0-9]+)/,""),d=d.replace(q+";",j+o[g]+";");else{var x=ADS_CHECKER.array_diff(o,g);0==x.length?1==o.length?
m[0]=o[0].replace(/_([0-9]+)/,""):(j=this.strReverse(q.replace(j,"")),m[0]=j.split(",")[0].replace(/_([0-9]+)/,""),d=d.replace(q+";",q+j+";")):(g=ADS_CHECKER.rand(0,x.length-1),m[0]=x[g].replace(/_([0-9]+)/,""),d=d.replace(q+";",q+","+x[g]+";"))}}this.cookie=d;if(2==f[m[0]]){for(var l=o=0;l<v[m[0]].length;l++)o=Math.max(o,this.cpd[m[0]-1][l].length);for(l=0;l<v[m[0]].length;l++){x=[];q=[];for(j=0;j<p[m[0]-1][l].length;j++)x.push(ADS_CHECKER.in_array_position(p[m[0]-1][l][j],s));for(j=0;j<y[m[0]-1][l].length;j++)q.push(ADS_CHECKER.in_array_position(y[m[0]-
1][l][j],s));if(0<q.length&&x.length<o){j=0;for(g=x.length;j<o-g;j++)x.push("m"+(1<o-g?"_"+j:""))}j="z"+r+"s"+m[0]+"_"+l+":";this.subCookie(d,j,0);j=!1;j=-1!=t[b].indexOf("m")?this.getMix(q,d,"z"+r+"sm"+m[0]+"_"+l+":"):this.getMix(x,d,"z"+r+"s"+m[0]+"_"+l+":");d=this.cookie;g="";if(!1===j||-1!=j.toString().indexOf("m"))if(0<q.length){var j=this.getMix(q,d,"z"+r+"sm"+m[0]+"_"+l+":"),d=this.cookie,g=0,g="string"==typeof s[j]?parseInt(s[j].replace(/_[0-9]/g,"")):s[j],e=new banner(a[g]);0<this.spamlstCp.length&&
0<this.spamBidCpd.length&&(this.fillterCpdShow(e,h[b]),p=this.cpd);1===e.iframe?(z.push(g),g=this.renderIframe("ads_zone"+r+"_banner"+e.bid,"banner"+(l+1),e.width,e.height)):g=e.renderBanner("ads_zone"+r+"_banner"+e.bid,r,Math.random(),"","banner"+(l+1))}else{if(g=this.slotBannerDefault(m[0],l+1),""==g&&this.cpd[m[0]-1][l].length)(j=ADS_CHECKER.in_array_position(p[m[0]-1][l][ADS_CHECKER.rand(0,this.cpd[m[0]-1][l].length-1)],s),g="string"==typeof s[j]?parseInt(s[j].replace(/_[0-9]/g,"")):s[j],e=new banner(a[g]),
0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,h[b]),p=this.cpd),1===e.iframe)?(z.push(g),g=this.renderIframe("ads_zone"+r+"_banner"+e.bid,"banner"+(l+1),e.width,e.height)):g=e.renderBanner("ads_zone"+r+"_banner"+e.bid,r,Math.random(),"","banner"+(l+1))}else(g="string"==typeof s[j]?parseInt(s[j].replace(/_[0-9]/g,"")):s[j],0==g&&(q=ADS_CHECKER.array_diff(this.cpd[m[0]-1][l],this.arr7k),0!=q.length&&(1==q.length?g="string"==typeof q[0]?q[0].replace(/_[0-9]/g,""):q[0]:(g=
Math.floor(Math.random()*q.length-1),g="string"==typeof s[g]?q[g].replace(/_[0-9]/g,""):q[g]))),0!=g)?(e=new banner(a[g]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,h[b]),p=this.cpd),1===e.iframe)?(z.push(g),g=this.renderIframe("ads_zone"+r+"_banner"+e.bid,"banner"+(l+1),e.width,e.height)):g=e.renderBanner("ads_zone"+r+"_banner"+e.bid,r,Math.random(),"","banner"+(l+1)):g=this.slotBannerDefault(m[0],l+1);C+=g}c=""==C?c:c.replace("slot"+m[0]+"_content",C)}else{x=[];q=
[];for(j=0;j<p[m[0]-1].length;j++)x.push(ADS_CHECKER.in_array_position(p[m[0]-1][j],s));for(j=0;j<y[m[0]-1].length;j++)q.push(ADS_CHECKER.in_array_position(y[m[0]-1][j],s));j=-1!=t[b].indexOf("m")?this.getMix(q,d,"z"+r+"sm"+m[0]+":"):this.getMix(x,d,"z"+r+"s"+m[0]+":");d=this.cookie;!1!==j?(g="string"==typeof s[j]?parseInt(s[j].replace(/_[0-9]/g,"")):s[j],0==g&&(q=ADS_CHECKER.array_diff(this.cpd[m[0]-1],this.arr7k),0!=q.length&&(1==q.length?g="string"==typeof q[0]?q[0].replace(/_[0-9]/g,""):q[0]:
(g=Math.floor(Math.random()*q.length-1),g="string"==typeof s[g]?q[g].replace(/_[0-9]/g,""):q[g]))),0!=g)?(e=new banner(a[g]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,h[b]),p=this.cpd),1===e.iframe)?(z.push(g),g=this.renderIframe("ads_zone"+r+"_banner"+e.bid,"banner0",e.width,e.height)):g=e.renderBanner("ads_zone"+r+"_banner"+j,r,Math.random(),"","banner0"):g=this.slotBannerDefault(m[0],"banner0"):g=this.slotBannerDefault(m[0],l+1);c=""==g?c:c.replace("slot"+m[0]+"_content",
g)}}b=this.spamBidCpd;l=0;for(m=b.length;l<m;l++)ADS_CHECKER.in_array(b[l].cid,_arAdmNotShow)&&(2==f[b[l].Idx]?this.cpd[b[l].Idx-1][b[l].sort-1]=ADS_CHECKER.array_diff(this.cpd[b[l].Idx-1][b[l].sort-1],[b[l].bid]):this.cpd[b[l].Idx-1]=ADS_CHECKER.array_diff(this.cpd[b[l].Idx-1],[b[l].bid])),ADS_CHECKER.in_array(b[l].cid,_arAdmShow)&&(2==f[b[l].Idx]?this.cpd[b[l].Idx-1][b[l].sort-1]=[b[l].bid]:this.cpd[b[l].Idx-1]=[b[l].bid]);for(b=0;b<n.length;b++)if(m=n[b].toString().split("_"),2==f[m[0]]){C="";
for(l=0;l<v[m[0]].length;l++){x=[];q=[];h=[];for(j=0;j<p[m[0]-1][l].length;j++)x.push(ADS_CHECKER.in_array_position(p[m[0]-1][l][j],s));for(j=0;j<y[m[0]-1][l].length;j++)q.push(ADS_CHECKER.in_array_position(y[m[0]-1][l][j],s));h=x;if(0<y[n[b]-1].length||0<w[n[b]])if(o=G-p[n[b]-1][l].length,0<o&&0<y[n[b]-1][l].length)for(j=0;j<o;j++)h.push("m"+(1<o?"_"+j:""));j="z"+r+"s"+n[b]+"_"+l+":";this.subCookie(d,j,0);h=this.getMix(h,d,j);d=this.cookie;-1!=h.toString().indexOf("m")||!1===h?0==y[m[0]-1][l].length?
g=this.slotBannerDefault(m[0],l+1):(j=this.getMix(q,d,"z"+r+"sm"+l+":"),d=this.cookie,g="string"==typeof s[j]?parseInt(s[j].replace(/_[0-9]/g,"")):s[j],e=new banner(a[g]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,[]),p=this.cpd),1===e.iframe)?(z.push(g),g=this.renderIframe("ads_zone"+r+"_banner"+e.bid,"banner"+(l+1),e.width,e.height)):g=e.renderBanner("ads_zone"+r+"_banner"+e.bid,r,Math.random(),"","banner"+(l+1)):(g="string"==typeof s[h]?parseInt(s[h].replace(/_[0-9]/g,
"")):s[h],0==g&&(q=ADS_CHECKER.array_diff(this.cpd[m[0]-1][l],this.arr7k),0!=q.length&&(1==q.length?g="string"==typeof q[0]?q[0].replace(/_[0-9]/g,""):q[0]:(g=Math.floor(Math.random()*q.length-1),g="string"==typeof s[g]?q[g].replace(/_[0-9]/g,""):q[g]))),0!=g)?(e=new banner(a[g]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,[]),p=this.cpd),1===e.iframe)?(z.push(g),g=this.renderIframe("ads_zone"+r+"_banner"+e.bid,"banner"+(l+1),e.width,e.height)):g=e.renderBanner("ads_zone"+
r+"_banner"+e.bid,r,Math.random(),"","banner"+(l+1)):g=this.slotBannerDefault(m[0],l+1);C+=g}c=""==C?c:c.replace("slot"+n[b]+"_content",C)}else{x=[];q=[];for(j=0;j<p[n[b]-1].length;j++)x.push(ADS_CHECKER.in_array_position(p[n[b]-1][j],s));for(j=0;j<y[n[b]-1].length;j++)q.push(ADS_CHECKER.in_array_position(y[n[b]-1][j],s));h=x;if(0<y[n[b]-1].length||0<w[n[b]]){o=G-p[n[b]-1].length;for(j=0;j<o;j++)h.push("m"+(1<o?"_"+j:""))}j="z"+r+"s"+n[b]+":";this.subCookie(d,j,0);h=this.getMix(h,d,j);d=this.cookie;
-1!=h.toString().indexOf("m")||!1===h?0!=y[n[b]-1].length?(j=this.getMix(q,d,"z"+r+"sm"+n[b]+":"),d=this.cookie,g="string"==typeof s[j]?parseInt(s[j].replace(/_[0-9]/g,"")):s[j],e=new banner(a[g]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,[]),p=this.cpd),1===e.iframe)?(z.push(g),g=this.renderIframe("ads_zone"+r+"_banner"+e.bid,"banner0",e.width,e.height)):g=e.renderBanner("ads_zone"+r+"_banner"+e.bid,r,Math.random(),"","banner0"):g=this.slotBannerDefault(n[b],0):(g=
"string"==typeof s[h]?parseInt(s[h].replace(/_[0-9]/g,"")):s[h],0==g&&(q=ADS_CHECKER.array_diff(this.cpd[m[0]-1],this.arr7k),0!=q.length&&(1==q.length?g="string"==typeof q[0]?q[0].replace(/_[0-9]/g,""):q[0]:(g=Math.floor(Math.random()*q.length-1),g="string"==typeof s[g]?q[g].replace(/_[0-9]/g,""):q[g]))),0!=g)?(e=new banner(a[g]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,[]),p=this.cpd),1===e.iframe)?(z.push(g),g=this.renderIframe("ads_zone"+r+"_banner"+e.bid,"banner0",
e.width,e.height)):g=e.renderBanner("ads_zone"+r+"_banner"+g,r,Math.random(),"","banner0"):g=this.slotBannerDefault(e.slotIdx,"banner0");c=""==g?c:c.replace("slot"+n[b]+"_content",g)}c=this.removeHtml(c);document.write(c);ADS_CHECKER.setStorage("_azs",d,"","/");0!=this.trks&&(e=ADS_CHECKER.getElementTop("ads_zone"+r+"_slot"+this.trks),0<e&&window.scrollTo(0,e));b=0;for(g=z.length;b<g;b++)c=document.getElementById("ads_zone"+r+"_banner"+z[b]),e=new banner(a[z[b]]),c=c.contentWindow?c.contentWindow.document:
c.contentDocument?c.contentDocument:c.document,e="<html><head><style>body{margin:0}</style></head><body>"+e.renderBanner("ads_zone"+r+"_banner"+z[b],r,Math.random(),"","banner"+e.sort)+"</body></html>",c.write(e),c.close()};
zone.prototype.getMix=function(a,c,d){var b=!1;if(0==a.length)return!1;if(1==a.length)return a[0];var h=this.subCookie(c,d,0),f=h.replace(d,"").split(","),n=ADS_CHECKER.array_diff(f,a),f=ADS_CHECKER.array_diff(a,f);""==h?0<a.length&&(b=ADS_CHECKER.rand(0,a.length-1),b=a[b],c+=d+b+";"):0<n.length?(c=c.replace(h+";",""),0<a.length&&(b=ADS_CHECKER.rand(0,a.length-1),b=a[b],c+=d+b+";")):0<f.length?(b=ADS_CHECKER.rand(0,f.length-1),b=f[b],c=c.replace(h+";",h+","+b+";")):(a=this.strReverse(h.replace(d,
"")),b=a.split(",")[0],c=c.replace(h+";",d+a+";"));this.cookie=c;return b};
zone.prototype.getSlotRun=function(a,c,d,b){this.subCookie(b,"Ver:",0);var h=this.style.effect,f=this.style.sort_banner_slot,n=this.style.banner_default,v=[],w=[],G=this.share,r=!1,s=[],z=[],t=this.spamBidCpd,h=this.style.effect,g=t.length,o=[];if(0<g)for(c=0;c<g;c++)ADS_CHECKER.in_array(t[c].cid,_arAdmShow)&&(ADS_CHECKER.in_array(t[c].Idx,o)||o.push(t[c].Idx),0==h[t[c].Idx]?(this.cpd[t[c].Idx-1]=[t[c].bid],this.cpm[t[c].Idx-1]=[]):0<t[c].sort&&(this.cpd[t[c].Idx-1][t[c].sort-1]=[t[c].bid],this.cpm[t[c].Idx-
1][t[c].sort-1]=[]));0<o.length&&(d=o);g=t=0;for(o=d.length;g<o;g++){var p=this.cpd[d[g]-1].join(",").replace(/,/g,""),m=this.cpm[d[g]-1].join(",").replace(/,/g,"");if(""!=p){w.push(d[g]);var j=0;if(2==h[d[g]])for(p=0;p<f[d[g]].length;p++)j=Math.max(j,this.cpd[d[g]-1][p].length);else j=this.cpd[d[g]-1].length;for(p=0;p<j;p++)s.push(d[g]+(1<j?"_"+p:""));t+=j}if(""!=m){m=0;v.push(d[g]);if(2==h[d[g]])for(p=0;p<f[d[g]].length;p++)m=Math.max(m,this.cpm[d[g]-1][p].length);else m=this.cpm[d[g]-1].length;
for(p=0;p<m;p++)z.push(d[g]+(1<m?"_"+p:""))}if(g==o-1)if(m=this.subCookie(b,"z"+a+"R"+c+":",0),0<t){j=s;if(0<v.length)for(p=0;p<G-t;p++)s.push(d[c]+"_m_"+p);var y=m.replace("z"+a+"R"+c+":","").split(",");1==s.length||""==m||y.length>s.length||0!=ADS_CHECKER.array_diff(y,s).length?(""!=m&&(b=b.replace(m+";","")),p=ADS_CHECKER.rand(0,j.length-1),r=j[p],1<s.length&&(b+="z"+a+"R"+c+":"+j[p]+";")):y.length==s.length&&0==ADS_CHECKER.array_diff(y,s).length&&0==ADS_CHECKER.array_diff(s,y).length?(r=this.strReverse(m.replace("z"+
a+"R"+c+":","")),p=r.split(","),b=b.replace(m+";","z"+a+"R"+c+":"+r+";"),-1!=p[0].indexOf("m")?(b=this.choseMix(a,c,z,b),r=b+"_m",b=this.cookie):r=p[0]):""==m?(p=ADS_CHECKER.rand(0,j.length-1),r=j[p],b+="z"+a+"R"+c+":"+j[p]+";"):(p=ADS_CHECKER.array_diff(y,j),r=ADS_CHECKER.array_diff(s,y),j=ADS_CHECKER.array_diff(j,y),0==p.length&&0!=j.length?(p=ADS_CHECKER.rand(0,j.length-1),b=b.replace(m+";",m+","+j[p]+";"),r=j[p]):(p=ADS_CHECKER.rand(0,r.length-1),b=b.replace(m+";",m+","+r[p]+";"),r=b=this.choseMix(a,
c,z,b),b=this.cookie))}else if(0==t&&0<v.length)b=this.choseMix(a,c,z,b),r=b+"_m",b=this.cookie;else if(0==t&&0==v.length){m=[];p=0;for(j=d.length;p<j;p++)0!=n[d[p]]&&m.push(d[p]);0<m.length&&(r=m[ADS_CHECKER.rand(0,m.length-1)]+"_d")}}this.cookie=b;return r};
zone.prototype.choseMix=function(a,c,d,b){var h=this.subCookie(b,"z"+a+"m"+c+":",0);if(1==d.length)return""!=h&&(b=b.replace(h+";","")),this.cookie=b,d[0];var f=h.replace("z"+a+"m"+c+":","").split(",");if(f.length>d.length||""!=f[0]&&0!=ADS_CHECKER.array_diff(f,d).length)return""!=h&&(b=b.replace(h+";","")),this.cookie=b,d[ADS_CHECKER.rand(0,d.length-1)];if(f.length==d.length&&0==ADS_CHECKER.array_diff(f,d).length&&0==ADS_CHECKER.array_diff(d,f).length)return d=this.strReverse(h.replace("z"+a+"m"+
c+":","")),f=d.split(","),this.cookie=b=b.replace(h+";","z"+a+"m"+c+":"+d+";"),f[0];d=ADS_CHECKER.array_diff(d,f);f=ADS_CHECKER.rand(0,d.length-1);this.cookie=b=""!=h?b.replace(h+";",h+","+d[f]+";"):b+("z"+a+"m"+c+":"+d[f]+";");return d[f]};
zone.prototype.drawEmpty=function(){for(var a=[],c=this.style.slots_rotate,d=this.style.effect,b=this.style.html,h=this.style.banner_default,f=0;f<this.style.slot;f++)a[f]=f+1;if(c)for(var f=0,n=c.length;f<n;f++){for(var a=ADS_CHECKER.array_diff(a,c[f]),v=[],w=0,G=c[f].length;w<G;w++)0!=h[c[f][w]]&&v.push(c[f][w]);0<v.length&&a.push(v[ADS_CHECKER.rand(0,v.length-1)])}f=0;for(n=a.length;f<n;f++)c=2!=d[a[f]]?this.slotBannerDefault(a[f],0):this.slotAllDefault(a[f]),b=""==c?b:b.replace("slot"+a[f]+"_content",
c);b=this.removeHtml(b);document.write(b)};zone.prototype.initZone=function(a){a?this.getBannerRun(a):this.drawEmpty();return!1};
zone.prototype.slotBannerDefault=function(a,c){if(0!=this.style.banner_default[a]){var d=this.style.banner_default[a],d=new banner({bannertype:0,bid:0,title:"",type:d.type,link:d.link,src:d.src,width:d.width,height:d.height,created:null,expired:null,slotIdx:a,attr:null,terms:d.terms,clicks:0,views:0,cpname:"",counter:!1,iframe:0,fix_ie:0,sort:0,link_clicks:null,link_views:null});d.process();if(d.bool)return d.renderBanner("ads_zone"+this.zoneid+"_banner"+c,this.zoneid,Math.random(),"","banner"+c)}return""};
zone.prototype.slotAllDefault=function(a){for(var c=this.style.sort_banner_slot[a].length,d="",b=0;b<c;b++)d+=this.slotBannerDefault(a,b+1);return d};zone.prototype.subCookie=function(a,c,d){c=a.indexOf(c,d);d=a.length-1;if(-1!=c){var b=a.indexOf(";z",c);-1==b&&(b=d);return a.substring(c,b)}return""};zone.prototype.strReverse=function(a){var c=a.indexOf(","),d=a.length;return-1==c?a:a.substring(c+1,d)+","+a.substring(0,c)};
zone.prototype.addBanners=function(a){var c=this.style.slot,d='<div id="ads_zone'+this.zoneid+'">'+this.style.html.replace(/id="slot/g,'id="ads_zone'+this.zoneid+"_slot")+"</div>";this.style.html='<div id="ads_zone'+this.zoneid+'">'+this.style.html.replace(/id="slot/g,'id="ads_zone'+this.zoneid+"_slot")+"</div>";this.style.css&&this.bindCSS(this.style.css);if(this.style&&0<this.style.slot){this.slots=[];for(var b=0;b<=c;b++)this.slots[b]=""}if(!this.initZone(a,d))return!1};
zone.prototype.getSizeStr=function(){this.width=0<parseInt(this.width)?"width:"+this.width+"px;":"";this.height=0<parseInt(this.height)?"height:"+this.height+"px;":""};zone.prototype.getZoneTag=function(){return"ads_zone"+this.zoneid};zone.prototype.append2slot=function(a,c){var d="slot"+c+"_content";this.style.html=this.style.html.replace(d,a+d)};zone.prototype.drawZoneTag=function(){};zone.prototype.hideEmptyZone=function(){};
zone.prototype.bindCSS=function(a){var c=document.createElement("style");c.type="text/css";document.getElementsByTagName("head")[0].appendChild(c);c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a))};



var _admTVCVideo=[];
function admParamTvc(){var a=0,b=0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(a=ADS_CHECKER.getQuery("_itvc"),a=""==a?0:parseInt(a),b=ADS_CHECKER.getCookie("__R"),b=""==b?0:parseInt(b)); if(_admTVCVideo.length>0){a=0;} if(a!=0){_admTVCVideo.push(a);}   return a+";"+b};

function TVCVZones(b){this.data=b;this.zoneid=b.ZONEID;this.imghost="http://admicro2.vcmedia.vn/adt/cpc/tvcads/";var e={hn:document.domain.replace("www.",""),url:function(){var a=top.location.toString(),c=document.domain.replace("www.","");return""==c?a:a.substring(a.indexOf(c)+c.length,a.length)}};this.logging=function(a,c,b,d){return c?b?encodeURIComponent("http://logging.admicro.vn/v?"+a.cid+";"+a.bid+";"+a.zid+";"+d+";-1;9;"+e.hn+";"+encodeURIComponent(e.url())):"http://logging.admicro.vn/"+("v?"+
a.cid+";"+a.bid+";"+a.zid+";"+d+";-1;9;"+e.hn+";"+encodeURIComponent(e.url())):b?encodeURIComponent("http://logging.admicro.vn/c?"+a.cid+";"+a.bid+";"+a.zid+";"+d+";-1;9;"+e.hn+";="+encodeURIComponent(e.url())+"&re="+encodeURIComponent(a.link)):"http://logging.admicro.vn/"+("c?"+a.cid+";"+a.bid+";"+a.zid+";"+d+";-1;9;"+e.hn+";="+encodeURIComponent(e.url())+"&re="+encodeURIComponent(a.link))};this.campWill=function(a){var c=[],b=[],d;for(d in a)if(void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER){if(!ADS_CHECKER.in_array(d,
b))for(var f=ADS_CHECKER.getCookie("__R"),e=ADS_CHECKER.getCookie("__RC"),f=","+f+",",e=","+e+",",g=0,h=a[d].length;g<h;g++){var i=","+a[d][g].l+",",j=/,[1|2|3],[1|2|3],[1|2|3],/g;if(-1!=i.indexOf(",,")||j.test(i)||-1!=i.indexOf(f)||-1!=i.indexOf(e)){c.push(d);break}}}else{g=0;for(h=a[d].length;g<h;g++)if(i=","+a[d][g].l+",",j=/,[1|2|3],[1|2|3],[1|2|3],/g,-1!=i.indexOf(",,")||j.test(i)){c.push(d);break}}return c};this.renderData=function(a){var c={},b=this.imghost+a.path,d,f;a.zid=this.zoneid;f=a.type;
c.zid=a.zid;c.cid=a.cid;c.bid=a.bid;c.type=f;c.titlebar=a.item.titlebar;c.duration=a.item.duration;c.img=b+a.item.img;c.video=b+a.video;c.linkview3rd=a.linkview3rd;c.view=this.logging(a,!0,!1,-1);c.adslink=this.logging(a,!1,!1,-1);c.action={};c.action.view=this.logging(a,!0,!1,1);c.action.click=this.logging(a,!1,!1,1);d="undefined"==typeof a.item.addon?"":b+a.item.addon;b="undefined"==typeof a.item.source?"":b+a.item.source;a=this.logging(a,!1,!1,"undefined"==typeof a.item.key?-1:a.item.key);c.bug=
1==f?null:{fromsec:6,source:b,wi:90,he:120,action:{opt:2==f?1:2,url:2==f?a:d,wi:null,he:null}};return c};this.choseData=function(a){for(var c=[],b=0,d=a.length;b<d;b++){var f=","+a[b].l+",",e=/,[1|2|3],[1|2|3],[1|2|3],/g;if(void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER){var g=ADS_CHECKER.getCookie("__R"),h=ADS_CHECKER.getCookie("__RC"),g=","+g+",",h=","+h+",";(-1!=f.indexOf(",,")||e.test(f)||-1!=f.indexOf(g)||-1!=f.indexOf(h))&&c.push(this.renderData(a[b]))}else(-1!=f.indexOf(",,")||
e.test(f))&&c.push(this.renderData(a[b]))}return c};b=this.campWill(b.NORMAL);0<b.length&&(b=this.choseData(this.data.NORMAL[b[Math.floor(Math.random()*b.length)]]),_ovelayShow=!1,_arPreRoll=b)}
function jsonreturn(){var b=document.domain;if(-1!=b.indexOf("dantri.com.vn")||-1!=b.indexOf("kenh14.vn"))for(var b=[587941,591635,592725,594879,598128,600647,605448,2012061311159708,610210],e=document.URL,a=0,c=b.length;a<c;a++)-1!=e.indexOf(b[a]+"")&&(_ovelayShow=!1,_arPreRoll=null);null!=_arPreRoll&&""!=_arPreRoll.linkview3rd&&document.images&&((new Image).src=_arPreRoll.linkview3rd);return null!=_arPreRoll&&0<_arPreRoll.length?(b=_arPreRoll[Math.floor(Math.random()*_arPreRoll.length)],document.images&&
((new Image).src=b.view),b):_arPreRoll};

var _arrCpmRun=[0],_arrCpm=[0];function cpmzone(a){this.zid=a}
cpmzone.prototype.logging=function(a,c,d){var b="http://",e="";c?(b+="logging.admicro.vn/_adv.gif",e=d?encodeURIComponent(b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1"):b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1"):(b+="logging.admicro.vn/_adc.html",e=d?encodeURIComponent(b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+
(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1&adm_rehttp="+escape(a.link)):b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1&adm_rehttp="+encodeURIComponent(a.link));return e};
cpmzone.prototype.renderBanner=function(a){var c="";switch(a.type){case "gif":case "jpeg":case "png":case "jpg":c+=this.renderBannerImage(a);break;case "swf":var d=!0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(d=ADS_CHECKER.flash);d?c+=this.renderBannerFlash(a):(a.src=a.src_bk,c+=this.renderBannerImage(a));break;case "html":c+=a.src}document.images?(new Image).src=this.logging(a,!0,!1):c+='<div style="background:url('+this.logging(a,!0,!1)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>';
return c+this.renderLinkViews(a.link_views)};cpmzone.prototype.renderLinkViews=function(a){var c="";null!=a&&(document.images?(new Image).src=a:c+='<div style="position:absolute;background:url('+a+');height:0; width:0" ><span style="height:0; width:0"></span></div>');return c};
cpmzone.prototype.renderBannerImage=function(a){var c='<img border="0" id="cpm'+this.zid+'" src="'+a.src+'"'+(a.width?' width="'+a.width+'"':"")+(a.height?' height="'+a.height+'"':""),c=c+"  />";return a.link?'<a href="'+this.logging(a,!1,!1)+'" target="_blank">'+c+"</a>":c};
cpmzone.prototype.renderBannerFlash=function(a){var c="",d=a.link?"alink1="+this.logging(a,!1,!0)+"&amp;atar1=_blank":"";""!=d&&(c+=' flashvars="'+d+'"');return'<embed  src="'+a.src+'" height="'+a.height+'" align="middle" width="'+a.width+'" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" '+c+' allowscriptaccess="always" wmode="transparent" quality="high" />'};
cpmzone.prototype.getData=function(a){var c=[],d=0,b=0,e="",f="",m=","+_arrCpmRun.join(",")+",",l=-1,j="",i=[],k=[],n=!0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(n=ADS_CHECKER.flash,d=parseInt(ADS_CHECKER.getQuery("i")),e=ADS_CHECKER.getCookie("__R"),f=ADS_CHECKER.getCookie("__RC"));for(var e=","+e+",",f=","+f+",",d=isNaN(d)?0:d,g=0,o=a.length;g<o;g++){var h=!1;if(-1==m.indexOf(","+a[g].bid+",")){null==a[g].l&&(a[g].l=0);var h=","+a[g].l+",",p=/,[1|2|3],[1|2|3],[1|2|3],/g,h=-1!=
h.indexOf(",,")||-1!=h.indexOf(",0,")||p.test(h)||-1!=h.indexOf(e)||-1!=h.indexOf(f);n||"swf"==a[g].type&&""==a[g].src_bk&&(h=!1);"undefined"!=typeof __arCPM4K&&void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&ADS_CHECKER.in_array(a[g].bid,__arCPM4K)&&(h=!1);h&&(b=d==a[g].bid?a[g].bid:b,l=d==a[g].bid?g:l,j=d==a[g].bid?a[g].width+"x"+a[g].height:j,c.push(g),1==this.db&&(300==a[g].width&&250==a[g].height||468==a[g].width&&90==a[g].height)?g!=l&&i.push(g):1==this.db&&(300==a[g].width&&600==
a[g].height||980==a[g].width&&90==a[g].height)&&k.push(g))}}if(0==c.length)return c;this.bz=b;if(1==this.db&&1<c.length){if("980x90"==j||"300x600"==j)return[l];if("300x250"==j||"468x90"==j)return 2>=i.length?i:[b,i[Math.floor(i.length*Math.random())]];if("980x90"==this.size||"300x600"==this.size){if(0<i.length&&0<k.length)return 0.5<=Math.random()?i:k;if(0<i.length)return i;if(0<k.length)return k}}else return c};
cpmzone.prototype.renderBannerExp=function(a){var c="";switch(a.type){case "gif":case "jpeg":case "png":case "jpg":case "swf":var d=!0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(d=ADS_CHECKER.flash);d?(c+=this.renderBannerFlashExp(a),document.images?(new Image).src=this.logging(a,!0,!1):c+='<div style="background:url('+this.logging(a,!0,!1)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>'):("swf"==a.type&&(a.src=a.src_bk),c+=this.renderBannerImage(a));
break;case "html":c+=a.src,document.images?(new Image).src=this.logging(a,!0,!1):c+='<div style="background:url('+this.logging(a,!0,!1)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>'}c+=this.renderLinkViews(a.link_views);d="";if("300"==a.width)return d='<div style="position: relative; clear:both; width: 300px; height: 250px;"><div id="rich_banner'+a.bid+'" style="top: 0px; right: 0px; clip: rect(0px, 980px, 250px, 680px); z-index: 1000; position: absolute;">',
d+c+"</div></div>";d="468";"980"==a.width&&(d="0");d='<div id="rich_banner'+a.bid+'" style="position: relative; height:'+a.height+"px; overflow:hidden; width:"+a.width+"px;  bottom: 0px; right: 0px; clip: rect(0px, 980px, 90px, "+d+'px); z-index: 1000;">';return d+c+"</div>"};
cpmzone.prototype.renderBannerFlashExp=function(a){var c="",d=a.link?"alink1="+this.logging(a,!1,!0)+"&amp;atar1=_blank":"",b="rich_banner"+a.bid;""!=d&&(c+=' flashvars="div_id='+b+"&"+d+"&file1="+a.src+"&file2="+a.src_exp+"&size="+a.width+"x"+a.height+'"');d=3;"300"==a.width&&(d=5);return'<embed height="300" align="middle" width="980" quality="high" wmode="transparent" allowscriptaccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" '+c+' src="http://admicro2.vcmedia.vn/htmlads/expand7k/expand.swf?v='+
d+'" />'};cpmzone.prototype.Shuffle=function(a){for(var c,d,b=a.length;b;c=parseInt(Math.random()*b),d=a[--b],a[b]=a[c],a[c]=d);return a};
cpmzone.prototype.show=function(a){this.size=a.size;this.db=a.is_db;var c=document.domain,c=c.replace("www.",""),d=c.split("."),b="",e="",c=document,f=c.createElement("style");"4k"==a.type&&"160x600"==a.size?(e="#cpmzone{clear:both;width:160px;height:auto;text-align:left;overflow:hidden;margin:0 auto}#cpmzone *{text-decoration:none;font-family:tahoma,arial!important;_font-family:tahoma, arial;font-size:11px;color:#333;text-transform:none!important;_text-transform:none;margin:0;padding:0}#cpmzone .ssvzContent{clear:both;overflow:hidden;background:#fff}#cpmzone .ssvzContent .ssvzMid{background:#FFF;height:auto}#cpmzone .ssvzHeader{background:url(http://admicro2.vcmedia.vn/adt/cpc/ssvborder.png) repeat-x 5px -18px;height:21px;line-height:21px}#cpmzone .ssvHeaderBr{background:url(http://admicro2.vcmedia.vn/adt/cpc/ssvtop.png) repeat-y 0 0;clear:both;overflow:hidden}#cpmzone .ssvzLogo{border:0;width:140px;height:21px;line-height:21px;background:url(http://admicro2.vcmedia.vn/adt/cpc/ssvtop.png) no-repeat -3px 0;margin:0;padding:0}#cpmzone .ssvzBuy{border:0;width:140px;height:21px;background:url(http://admicro2.vcmedia.vn/adt/cpc/ssvtop.png) no-repeat -3px -21px}#cpmzone #cpmzone_items{clear:both;margin:0}#cpmzone_items .adv_items{clear:both;height:216px;overflow:hidden;padding-top:5px;padding-right:7px;margin-left:7px}#cpmzone_items .ssvzBorder{background:#e5e5e5;height:1px}#cpmzone .ssvzclear,#cpmzone_items .adv_items .ssvzimage{clear:both}",b=
b+'<div class="ssvHeaderBr"><div class="ssvHeaderBrRight"><div class="ssvzHeader">'+('<a title="Mua qu\u1ea3ng c\u00e1o"  href="http://admarket.admicro.vn/?utm_source=box_'+d[0]+'&utm_medium=banner&utm_campaign=PR06201" target="_blank"><img vspace="0" hspace="0" class="ssvzBuy" src="http://admicro2.vcmedia.vn/adt/cpc/zoneimages/spacer.gif" border="0" align="right" /></a></div></div></div>'),b=b+'<div class="ssvzContent"><div class="ssvzRight"><div class="ssvzMid"><div id="cpmzone_items"></div><div class="ssvzclear"><span></span></div></div></div></div><div class="ssvHeaderBrRight"><div class="ssvzHeader"><div class="ssvHeaderBrRight"> '+
('<a title="Mua qu\u1ea3ng c\u00e1o" href="http://admarket.admicro.vn/?utm_source=box_'+d[0]+'&utm_medium=banner&utm_campaign=PR06201" target="_blank"><img class="ssvzLogo" vspace="0" hspace="0" border="0" align="left" src="http://admicro2.vcmedia.vn/adt/cpc/zoneimages/spacer.gif"></a></div></div></div>')):"4k"==a.type&&"200x167"==a.size?e="#cpmzone{clear:both;width:200px;height:auto;text-align:left;overflow-x:hidden;margin:0 auto} #cpmzone img, #cpmzone embed, #cpmzone object{width:200px; height:167px;}":
("4k"==a.type||"7k"==a.type)&&0==a.is_db?e="#cpmzone{clear:both;text-align:left;overflow-x:hidden;margin:0 auto}":"7k"==a.type&&"980x90"==a.size?(e="#cpmzone{clear:both;width:980px;height:auto;text-align:left;overflow-x:hidden;margin:0 auto}#cpmzone_banner_left{float:left; width:468px;}#cpmzone_banner_right{float:right; width:468px;},#cpmzone_banner{clear:both; width:980px; margin:0 auto;}",b+='<div id="cpmzone_items"></div>'):"7k"==a.type&&"300x600"==a.size&&(e="#cpmzone{clear:both;width:300px;height:auto;text-align:left;overflow-x:hidden;margin:0 auto}#cpmzone_banner{clear:both;}",
b+='<div id="cpmzone_items"></div>');b=b.replace(/cpmzone/g,"cpmzone_"+this.zid);f.type="text/css";c.getElementsByTagName("head")[0].appendChild(f);e=e.replace(/cpmzone/g,"cpmzone_"+this.zid);f.styleSheet?f.styleSheet.cssText=e:f.appendChild(c.createTextNode(e));d=c.getElementById("cpmzone_"+this.zid);try{d?d.innerHTML=b:c.write('<div id="cpmzone_'+this.zid+'">'+b+"</div>")}catch(m){}d=this.getData(a.lst);b="";e=a.df;0<d.length?(d=this.Shuffle(d),"4k"==a.type?(b+=this.renderBanner(a.lst[d[0]]),"160x600"==
a.size&&(1<d.length?b=b+'<div style="clear:both; height:10px;"><span></span></div>'+this.renderBanner(a.lst[d[0]]):0<a.df.length&&(b+='<div style="clear:both; height:10px;"><span></span></div>',e=this.Shuffle(e),b+=this.renderBanner(e[0])))):"7k"==a.type&&("300x600"==a.size||"980x90"==a.size?(f=a.lst[d[0]],"300x600"==a.size?(b=""!=f.src_exp?b+this.renderBannerExp(f):b+this.renderBanner(f),600!=f.height&&(1<d.length?(b+='<div style="clear:both; height:10px;"><span></span></div>',f=a.lst[d[1]],b=""!=
f.src_exp?b+this.renderBannerExp(f):b+this.renderBanner(f)):0<a.df.length&&(b+='<div style="clear:both; height:10px;"><span></span></div>',e=this.Shuffle(e),f=e[0],b+=this.renderBanner(f)))):980==f.width?b=""!=f.src_exp?b+this.renderBannerExp(f):b+this.renderBanner(f):(b=""!=f.src_exp?b+('<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBannerExp(f)+"</div>"):b+('<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBanner(f)+"</div>"),1<d.length?(f=a.lst[d[1]],b=""!=f.src_exp?b+('<div id="cpmzone_'+
this.zid+'_banner_right">'+this.renderBannerExp(f)+"</div>"):b+('<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(f)+"</div>")):0<a.df.length&&(e=this.Shuffle(e),f=e[0],b+='<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(f)+"</div>"))):b+=this.renderBanner(a.lst[d[0]]))):"4k"==a.type&&"160x600"==a.size?(d=document.getElementById("cpmzone_"+this.zid),d.style.display="none"):"980x90"==a.size||"300x600"==a.size?0<e.length&&(1<e.length?"980x90"==a.size?(b+='<div id="cpmzone_'+
this.zid+'_banner_left">'+this.renderBanner(e[0])+"</div>",b+='<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(e[1])+"</div>"):(b+=this.renderBanner(a.lst[d[0]]),b=b+'<div style="clear:both; height:10px;"><span></span></div>'+this.renderBanner(a.lst[d[1]])):"980x90"==a.size?(b+='<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBanner(e[0])+"</div>",b+='<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(e[0])+"</div>"):(b+=this.renderBanner(a.lst[d[0]]),b=b+'<div style="clear:both; height:10px;"><span></span></div>'+
this.renderBanner(a.lst[d[0]]))):0<e.length?b+=this.renderBanner(a.df[arr1[Math.floor(Math.random()*arr1.length)]]):(d=document.getElementById("cpmzone_"+this.zid),d.style.display="none");("4k"==a.type&&"160x600"==a.size||"7k"==a.type&&"300x600"==a.size||"7k"==a.type&&"980x90"==a.size?c.getElementById("cpmzone_"+this.zid+"_items"):c.getElementById("cpmzone_"+this.zid)).innerHTML=b};


function adoverlay(){if(!_ovelayShow)return null;this.domain="http://"+document.domain+"/";this.Shuffle=function(b){for(var c,d,e=b.length;e;c=parseInt(Math.random()*e),d=b[--e],b[e]=b[c],b[c]=d);return b};this.logging=function(b,c,d){return c?"http://logging.admicro.vn/_adc.html?"+b:d?"http://logging.admicro.vn/_zc.1.gif?"+b:"http://logging.admicro.vn/_adv.gif?"+b};this.FlashText=function(b){return b.replace(/<(span|strong|b)([^>]*)>(.*?)<\/(span|strong|b)>/g,"$3")};if("undefined"!=typeof _ssv_tvc){var h=
_ssv_tvc.z,c=_ssv_tvc.data,g=[],d=[],e=",0,",i=",0,";if("undefined"!=typeof ADS_CHECKER)var e=a=ADS_CHECKER.getCookie("__R"),b=ADS_CHECKER.getCookie("__RC"),e=""==e?",0,":","+e+",",i=""==b?",0,":","+b+",";for(var b=0,j=c.length;b<j;b++){var f=","+c[b].l+",";(-1!=f.indexOf(",1,2,3,")||-1!=f.indexOf(",3,2,1,")||-1!=f.indexOf(",,")||-1!=f.indexOf(e)||-1!=f.indexOf(i))&&d.push(c[b])}c=[];d=this.Shuffle(d);if(3>=d.length)c=d;else for(b=0;3>b;b++)c.push(d[b]);if(c)for(b=0;b<c.length;b++)c[b].title=this.FlashText(c[b].title),
c[b].content=this.FlashText(c[b].content),d={},d.adThumb=c[b].image,d.adTitle=c[b].title,d.adContent=c[b].content,d.adLink=this.logging("adm_domain="+encodeURIComponent(document.URL)+"&adm_campaign="+c[b].cid+"&adm_aditem="+c[b].bid+"&adm_zoneid="+h+"&adm_channelid=-1&adm_rehttp="+encodeURIComponent(c[b].link+(-1!=c[b].descr.indexOf("muachung.vn")?"?ref="+encodeURIComponent(document.URL)+"&bi="+c[b].bid+"&ci="+c[b].cid:"")),!0,!0),d.adDomain=c[b].descr,d.adView=this.logging("adm_aditem="+c[b].bid+
"&adm_campaign="+c[b].cid+"&adm_channelid=-1&adm_domain="+encodeURIComponent(document.URL)+"&adm_zoneid="+h,!1,!1),g.push(d);return 0<g.length?g:null}return null};


var _preloadRun={preroll:{cpc:[],cpm:[]},postroll:{cpc:[],cpm:[]}};

function R_list_mc(f){f=null==f||"preroll"==f?"preroll":"postroll";if(list_item_mc){this.Shuffle=function(a){for(var b,c,d=a.length;d;b=parseInt(Math.random()*d),c=a[--d],a[d]=a[b],a[b]=c);return a};this.domain="http://"+document.domain+"/";this.logging=function(a,b,c){return b?"http://logging.admicro.vn/_adc.html?"+a:c?"http://logging.admicro.vn/_zc.1.gif?"+a:"http://logging.admicro.vn/_adv.gif?"+a};if(0==_preloadRun.preroll.cpc.length){var a=ADS_CHECKER.getCookie("__R"),e=ADS_CHECKER.getCookie("__RC"),
g=list_item_mc.cpc.data,c={},h=g.length;if("0"==a||"0"==e||""==a)for(var b=a=0;b<h;b++){var d=","+g[b].l.toString()+",";if(-1!=d.indexOf(",1,2,3,")||",,"==d)d=g[b].CPMid,c[d]||(c[d]=[]),c[d].push(g[b])}else if(a=","+a+",",e=","+e+",",0!=a||0!=e)for(b=0;b<h;b++)if(d=","+g[b].l.toString()+",",-1!=d.indexOf(a)||-1!=d.indexOf(e))d=g[b].CPMid,c[d]||(c[d]=[]),c[d].push(g[b]);for(h=0;h<c.length;h++)if(2>c[h].length)for(var i=ADS_CHECKER.array_diff(g,c),j=i.length,b=0;b<j;b++)if(d=","+i[b].la.toString()+
",",-1!=d.indexOf(a)||-1!=d.indexOf(e))d=i[b].CPMid,c[d]||(c[d]=[]),c[d].push(i[b]);a=[];for(b in c)a.push(b),1==c[b].length&&c[b].push(c[b][0]);a=this.Shuffle(a);if(0==_preloadRun.preroll.cpm.length){b=0;for(e=list_item_mc.cpm.length;b<e;b++)if(list_item_mc.cpm[b].bid==a[0]){if(_preloadRun.preroll.cpm=list_item_mc.cpm[b],c[a[0]]=this.Shuffle(c[a[0]]),_preloadRun.preroll.cpc.push(c[a[0]][0]),_preloadRun.preroll.cpc.push(c[a[0]][1]),1==a.length){_preloadRun.postroll.cpm=b;c[a[0]]=this.Shuffle(c[a[0]]);
_preloadRun.postroll.cpc.push(c[a[0]][0]);_preloadRun.postroll.cpc.push(c[a[0]][1]);break}}else 1<a.length&&list_item_mc.cpm[b].bid==a[1]&&(_preloadRun.postroll.cpm=list_item_mc.cpm[b],c[a[1]]=this.Shuffle(c[a[1]]),_preloadRun.postroll.cpc.push(c[a[1]][0]),_preloadRun.postroll.cpc.push(c[a[1]][1]))}}c="";b=document.url;a=_preloadRun[f].cpc;e=_preloadRun[f].cpm;c="_domain="+escape(this.domain)+"&_ci="+a[0].cid+"|"+a[0].bid+","+a[1].cid+"|"+a[1].bid+"&_zid="+list_item_mc.cpc.z[f];return{cpm:{link:"",
title:e.title,image:e.image,view:this.logging("adm_domain="+escape(this.domain)+"&adm_campaign="+e.cid+"&amp;adm_aditem="+e.bid+"&adm_zoneid="+e.zoneid+"&adm_channelid=-1&adm_random="+Math.random(),!1,!1),click:this.logging("adm_domain="+escape(this.domain)+"&adm_campaign="+e.cid+"&adm_aditem="+e.bid+"&adm_zoneid="+e.zoneid+"&adm_channelid=-1&adm_rehttp="+escape(e.link),!0,!0)},cpc1:{title:a[0].title.replace(/color:#([a-f0-9]{1,6});\">([^<]+)/g,'"><font color="#$1">$2</font>'),link:"",content:a[0].content.replace(/color:#([a-f0-9]{1,6});\">([^<]+)/g,
'"><font color="#$1">$2</font>'),descr:a[0].descr,image:a[0].image,view:this.logging(c,!1,!0),click:this.logging("adm_domain="+escape(this.domain)+"&adm_campaign="+a[0].cid+"&adm_aditem="+a[0].bid+"&adm_zoneid="+list_item_mc.cpc.z[f]+"&adm_channelid=-1&adm_rehttp="+escape(a[0].link+(-1!=a[0].descr.indexOf("muachung.vn")?"?ref="+b+"&bi="+a[0].bid+"&ci="+a[0].cid:"")),!0,!0)},cpc2:{title:a[1].title.replace(/color:#([a-f0-9]{1,6});\">([^<]+)/g,'"><font color="#$1">$2</font>'),link:"",content:a[1].content.replace(/color:#([a-f0-9]{1,6});\">([^<]+)/g,
'"><font color="#$1">$2</font>'),descr:a[1].descr,image:a[1].image,view:this.logging(c,!1,!0),click:this.logging("adm_domain="+escape(this.domain)+"&adm_campaign="+a[1].cid+"&adm_aditem="+a[1].bid+"&adm_zoneid="+list_item_mc.cpc.z[f]+"&adm_channelid=-1&adm_rehttp="+escape(a[1].link+(-1!=a[1].descr.indexOf("muachung.vn")?"?ref="+b+"&bi="+a[1].bid+"&ci="+a[1].cid:"")),!0,!0)}}}};

var wPrototype={wdHeight:function(){var a,b=document;"number"==typeof window.innerWidth?a=window.innerHeight:b.documentElement&&b.documentElement.clientHeight?a=b.documentElement.clientHeight:b.body&&b.body.clientHeight&&(a=b.body.clientHeight);return a},wdWidth:function(){var a,b=document;"number"==typeof window.innerWidth?a=window.innerWidth:b.documentElement&&b.documentElement.clientWidth?a=b.documentElement.clientWidth:b.body&&b.body.clientWidth&&(a=b.body.clientWidth);return a},getElementTop:function(a){var b=
document;if(b.getElementById)var c=b.getElementById(a);else b.all&&(c=b.all[a]);if(null!=c){yPos=c.offsetTop;for(tempEl=c.offsetParent;null!=tempEl;)yPos+=tempEl.offsetTop,tempEl=tempEl.offsetParent;return yPos}return 150},getElementWidth:function(a){return document.getElementById(a).clientWidth},getElementLeft:function(a){var b,c=document;c.getElementById?b=c.getElementById(a):c.all&&(b=c.all[a]);a=b.offsetLeft;for(b=b.offsetParent;null!=b;)a+=b.offsetLeft,b=b.offsetParent;return a},scrollTop:function(){var a=
document,b=a.body.scrollTop;0==b&&(b=window.pageYOffset?window.pageYOffset:a.body.parentElement?a.body.parentElement.scrollTop:0);return b},scrollLeft:function(){var a=document,b=window.pageXOffset?window.pageXOffset:0,c=a.documentElement?a.documentElement.scrollLeft:0,a=a.body?a.body.scrollLeft:0,b=b?b:0;if(c&&(!b||b>c))b=c;return a&&(!b||b>a)?a:b},bdWidth:function(){var a=document;return bodyWidth=Math.max(Math.max(a.body.scrollWidth,a.documentElement.scrollWidth),Math.max(a.body.offsetWidth,a.documentElement.offsetWidth),
Math.max(a.body.clientWidth,a.documentElement.clientWidth))},bdHeight:function(){var a=document;return Math.max(Math.max(a.body.scrollHeight,a.documentElement.scrollHeight),Math.max(a.body.offsetHeight,a.documentElement.offsetHeight),Math.max(a.body.clientHeight,a.documentElement.clientHeight))}};
//bannerdefault

document.write('<script language="javascript" src="http://admicro1.vcmedia.vn/cpc/ssvzone_default.js"><\/script><script language="javascript" src="http://admicro1.vcmedia.vn/cpc/ssvzone_tvc.js"><\/script>');

function _admloadJs(c,a){var b=document.createElement("script");document.getElementsByTagName("head")[0].appendChild(b);b.onload=function(){"function"==typeof a&&a();a=null};b.onreadystatechange=function(){if(4==b.readyState||"complete"==b.readyState)"function"==typeof a&&a(),a=null};b.src=c}_admloadJs("http://logging.admicro.vn/_cpm4k.js");

(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="http://admicro1.vcmedia.vn/core/adm_tracking.js?id="+Math.random();var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();var _admSticky=[],_admStickyId=[],_admFSticky=200,_admAppBanner=[],admURL=document.URL,htmladstest="";

/*
(function(){
var _urlDomain=document.domain;
	if(_urlDomain.indexOf('dantri.com.vn') ==-1 &&  _urlDomain.indexOf('vietnamnet.vn') ==-1 && _urlDomain.indexOf('kenh14.vn') ==-1){
		document.write('<div style="display:none; height:0; width:0;"><iframe src="http://admicro2.vcmedia.vn/adt/liveads/" style="width:0; height:0; display:none;" wdith="0" height="0"></iframe></div>');
		var img=new Image(),img1=new Image();
		img.src='http://mb.logging.admicro.vn:8090/v7k?1002874;1;972;-1;19;9;1;-1;kenh14.vn;?/thoi-trang.chn';
		img1.src='http://mb.logging.admicro.vn:8090/v7k?1002874;2;972;-1;19;9;1;-1;kenh14.vn;?/thoi-trang.chn';
	}
})();
*/